package enrollmentsystem;

public class AdminForm extends javax.swing.JFrame {

    /**
     * Creates new form AdminForm
     */
    public AdminForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_bg = new javax.swing.JPanel();
        panel_navigator = new javax.swing.JPanel();
        btn_one = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_two = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_three = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_four = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panel_body_basic = new javax.swing.JPanel();
        basic_info = new javax.swing.JPanel();
        lbl_name = new javax.swing.JLabel();
        lbl_birthdate = new javax.swing.JLabel();
        lbl_nationality = new javax.swing.JLabel();
        txtf_name = new javax.swing.JTextField();
        txtf_nationality = new javax.swing.JTextField();
        txtf_bdate = new javax.swing.JTextField();
        txtf_civil = new javax.swing.JTextField();
        lbl_civil = new javax.swing.JLabel();
        lbl_gender = new javax.swing.JLabel();
        lbl_religion = new javax.swing.JLabel();
        txtf_religion = new javax.swing.JTextField();
        lbl_mobile = new javax.swing.JLabel();
        txtf_mobile = new javax.swing.JTextField();
        lbl_email = new javax.swing.JLabel();
        txtf_email = new javax.swing.JTextField();
        radbtn_male = new javax.swing.JRadioButton();
        radbtn_female = new javax.swing.JRadioButton();
        basic_educational = new javax.swing.JPanel();
        name1 = new javax.swing.JLabel();
        level1 = new javax.swing.JLabel();
        txtf_name1 = new javax.swing.JTextField();
        txtf_level1 = new javax.swing.JTextField();
        name3 = new javax.swing.JLabel();
        txtf_name3 = new javax.swing.JTextField();
        txtf_name4 = new javax.swing.JTextField();
        name4 = new javax.swing.JLabel();
        btn_oked = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_navigator.setBackground(new java.awt.Color(0, 102, 153));
        panel_navigator.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_one.setBackground(new java.awt.Color(242, 213, 103));

        jLabel1.setText("Basic Information");

        javax.swing.GroupLayout btn_oneLayout = new javax.swing.GroupLayout(btn_one);
        btn_one.setLayout(btn_oneLayout);
        btn_oneLayout.setHorizontalGroup(
            btn_oneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_oneLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        btn_oneLayout.setVerticalGroup(
            btn_oneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        panel_navigator.add(btn_one, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 210, 60));

        btn_two.setBackground(new java.awt.Color(242, 213, 103));

        jLabel2.setText("Course Description");

        javax.swing.GroupLayout btn_twoLayout = new javax.swing.GroupLayout(btn_two);
        btn_two.setLayout(btn_twoLayout);
        btn_twoLayout.setHorizontalGroup(
            btn_twoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_twoLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel2)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        btn_twoLayout.setVerticalGroup(
            btn_twoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        panel_navigator.add(btn_two, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 210, 60));

        btn_three.setBackground(new java.awt.Color(242, 213, 103));

        jLabel3.setText("Family");

        javax.swing.GroupLayout btn_threeLayout = new javax.swing.GroupLayout(btn_three);
        btn_three.setLayout(btn_threeLayout);
        btn_threeLayout.setHorizontalGroup(
            btn_threeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_threeLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel3)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        btn_threeLayout.setVerticalGroup(
            btn_threeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        panel_navigator.add(btn_three, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 210, 60));

        btn_four.setBackground(new java.awt.Color(242, 213, 103));

        jLabel4.setText("Validation");

        javax.swing.GroupLayout btn_fourLayout = new javax.swing.GroupLayout(btn_four);
        btn_four.setLayout(btn_fourLayout);
        btn_fourLayout.setHorizontalGroup(
            btn_fourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_fourLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel4)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        btn_fourLayout.setVerticalGroup(
            btn_fourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        panel_navigator.add(btn_four, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 210, 60));

        panel_bg.add(panel_navigator, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 580));

        panel_body_basic.setBackground(new java.awt.Color(244, 243, 243));
        panel_body_basic.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        basic_info.setBackground(new java.awt.Color(244, 243, 243));
        basic_info.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Basic Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Impact", 0, 18), new java.awt.Color(0, 102, 153))); // NOI18N

        lbl_name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_name.setText("Name:");

        lbl_birthdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_birthdate.setText("Birthdate:");

        lbl_nationality.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_nationality.setText("Nationality:");

        txtf_name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtf_nationality.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtf_bdate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtf_civil.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lbl_civil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_civil.setText("Civil Status:");

        lbl_gender.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_gender.setText("Gender:");

        lbl_religion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_religion.setText("Religion:");

        txtf_religion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lbl_mobile.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_mobile.setText("Mobile #");

        txtf_mobile.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lbl_email.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_email.setText("Email:");

        txtf_email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        radbtn_male.setText("Male");

        radbtn_female.setText("Female");

        javax.swing.GroupLayout basic_infoLayout = new javax.swing.GroupLayout(basic_info);
        basic_info.setLayout(basic_infoLayout);
        basic_infoLayout.setHorizontalGroup(
            basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basic_infoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(basic_infoLayout.createSequentialGroup()
                        .addGroup(basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_gender)
                            .addComponent(lbl_religion)
                            .addComponent(lbl_mobile))
                        .addGroup(basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(basic_infoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtf_religion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtf_mobile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(basic_infoLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(radbtn_male)
                                .addGap(18, 18, 18)
                                .addComponent(radbtn_female))))
                    .addGroup(basic_infoLayout.createSequentialGroup()
                        .addGroup(basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_nationality)
                            .addComponent(lbl_civil))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtf_civil, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtf_nationality, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(basic_infoLayout.createSequentialGroup()
                        .addGroup(basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_name, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_birthdate, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtf_name, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtf_bdate, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        basic_infoLayout.setVerticalGroup(
            basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basic_infoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_name)
                    .addComponent(txtf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_email)
                    .addComponent(txtf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_birthdate)
                    .addComponent(txtf_bdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtf_nationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nationality))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtf_civil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_civil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_gender)
                    .addComponent(radbtn_male)
                    .addComponent(radbtn_female))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtf_religion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_religion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(basic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtf_mobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_mobile))
                .addGap(42, 42, 42))
        );

        panel_body_basic.add(basic_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 23, -1, 255));

        basic_educational.setBackground(new java.awt.Color(244, 243, 243));
        basic_educational.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Educational Background", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Impact", 0, 18))); // NOI18N

        name1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        name1.setText("Secondaray:");

        level1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        level1.setText("Primary:");

        txtf_name1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtf_level1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        name3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        name3.setText("Year Ended:");

        txtf_name3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtf_name4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        name4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        name4.setText("Year Ended:");

        btn_oked.setText("OK");

        javax.swing.GroupLayout basic_educationalLayout = new javax.swing.GroupLayout(basic_educational);
        basic_educational.setLayout(basic_educationalLayout);
        basic_educationalLayout.setHorizontalGroup(
            basic_educationalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basic_educationalLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(basic_educationalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(basic_educationalLayout.createSequentialGroup()
                        .addGroup(basic_educationalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(level1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(name3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(4, 4, 4)
                        .addGroup(basic_educationalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtf_level1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtf_name3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(basic_educationalLayout.createSequentialGroup()
                        .addGroup(basic_educationalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(name1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(basic_educationalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtf_name1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtf_name4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basic_educationalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_oked)
                .addContainerGap())
        );
        basic_educationalLayout.setVerticalGroup(
            basic_educationalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basic_educationalLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(basic_educationalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name1)
                    .addComponent(txtf_name1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(basic_educationalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name4)
                    .addComponent(txtf_name4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(basic_educationalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basic_educationalLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(level1))
                    .addComponent(txtf_level1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(basic_educationalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basic_educationalLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(name3))
                    .addComponent(txtf_name3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_oked)
                .addContainerGap())
        );

        panel_body_basic.add(basic_educational, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 289, 620, -1));

        panel_bg.add(panel_body_basic, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 640, 580));

        getContentPane().add(panel_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showHome(){
        //panel_basic.setVisible(true);
        //panel_course.setVisible(false);
        //panel_display.setVisible(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel basic_educational;
    private javax.swing.JPanel basic_info;
    private javax.swing.JPanel btn_four;
    private javax.swing.JButton btn_oked;
    private javax.swing.JPanel btn_one;
    private javax.swing.JPanel btn_three;
    private javax.swing.JPanel btn_two;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbl_birthdate;
    private javax.swing.JLabel lbl_civil;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_gender;
    private javax.swing.JLabel lbl_mobile;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_nationality;
    private javax.swing.JLabel lbl_religion;
    private javax.swing.JLabel level1;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel name4;
    private javax.swing.JPanel panel_bg;
    private javax.swing.JPanel panel_body_basic;
    private javax.swing.JPanel panel_navigator;
    private javax.swing.JRadioButton radbtn_female;
    private javax.swing.JRadioButton radbtn_male;
    public javax.swing.JTextField txtf_bdate;
    public javax.swing.JTextField txtf_civil;
    public javax.swing.JTextField txtf_email;
    public javax.swing.JTextField txtf_level1;
    public javax.swing.JTextField txtf_mobile;
    public javax.swing.JTextField txtf_name;
    public javax.swing.JTextField txtf_name1;
    public javax.swing.JTextField txtf_name3;
    public javax.swing.JTextField txtf_name4;
    public javax.swing.JTextField txtf_nationality;
    public javax.swing.JTextField txtf_religion;
    // End of variables declaration//GEN-END:variables
}
